### PR TITLE
fix(JS tests): fix outdated testdata

### PR DESCRIPTION
**Pull request by elsapet**
## Description
Branch was out-of-date with `main`, which meant testdata files were missing secure helmet lines and were failing for reasons unexpected.

## Checklist

- [ ] I've added test coverage that shows my fix or feature works as expected.
- [ ] I've updated or added documentation if required.
- [ ] I've included usage information in the description if CLI behavior was updated or added.
- [ ] PR title follows [Conventional Commits](https://www.conventionalcommits.org/) format

### CODE REVIEW

**Review by didroe — APPROVED** [review]
Not for this PR but, we really need to scope the integration tests to a single rule again. Adding new rules shouldn't require updating all the other tests.

**Review by cfabianski — APPROVED** [review]

**Comment by cfabianski** [comment]
> Not for this PR but, we really need to scope the integration tests to a single rule again. Adding new rules shouldn't require updating all the other tests.

It's annoying I agree

**Comment by elsapet** [comment]
I agree with the absence rules it is a bit annoying, but there are some cases where it may be useful to run all rules against your test data - it would tell you if you were duplicating an existing rule, for example. Not sure what the best balance is here.

**Comment by vjerci** [comment]
> Not for this PR but, we really need to scope the integration tests to a single rule again. Adding new rules shouldn't require updating all the other tests.

Imho it's a good thing to have all rules running on tests, otherwise you wouldn't even know you have duplicate rules detection. Also in most cases you'll only need to update 1 or 2 similar rules snapshots.
I think the root of problem here is that we have rules which are very close to being duplicates. Those rules should probably be narrowed in scope of code they detect, removed alltogether, or detect only single from two available or some other solution.. Feels like that's a product problem that we're now trying to solve trough technicalities.

**Pull request merged**
