### PR TITLE
docs: add update instructions to installation page

### LINKED ISSUE #813: Docs: Adding "Upgrade" instruction
It would be helpful to add an "upgrade/update" instruction page in the doc below the "installation" one:
https://docs.bearer.com/reference/installation/

### PR DESCRIPTION
**Pull request by markmichon**
## Description
Updates installation instructions to include update instructions for each installation method.

## Related
- Close #813 

## Checklist

- [ ] I've added test coverage that shows my fix or feature works as expected.
- [ ] I've updated or added documentation if required.
- [ ] I've included usage information in the description if CLI behavior was updated or added.
- [x] PR title follows [Conventional Commits](https://www.conventionalcommits.org/) format

### CODE REVIEW

**Comment by gotbadger** [comment]
@markmichon I think the docker one does actually need action in some cases if you are using latest to get the new version you need to do something like

```
docker image pull bearer/bearer:latest-amd64
```

**Comment by cfabianski** [comment]
How about we create a totally new page/section dedicated to update/upgrade?
That way we could link it up with the message when we detect it's not the latest?

**Comment by markmichon** [comment]
@cfabianski I'm more inclined to have it be a dedicated section at the bottom of `installation` and we could link to `installation#update`. Worried about page fatigue. Thoughts?

**Comment by cfabianski** [comment]
> @cfabianski I'm more inclined to have it be a dedicated section at the bottom of `installation` and we could link to `installation#update`. Worried about page fatigue. Thoughts?

new section is good enough yes.
Wanna update this message too with the link? https://github.com/Bearer/bearer/blob/dc35d997c67c1719fae83b4adc77e4f4b7476b6f/pkg/commands/artifact/run.go#L229

**Comment by markmichon** [comment]
> > @cfabianski I'm more inclined to have it be a dedicated section at the bottom of `installation` and we could link to `installation#update`. Worried about page fatigue. Thoughts?
> 
> new section is good enough yes. Wanna update this message too with the link?
> 
> https://github.com/Bearer/bearer/blob/dc35d997c67c1719fae83b4adc77e4f4b7476b6f/pkg/commands/artifact/run.go#L229

@cfabianski we can, but that's out of scope of this PR. Rather not tie upgrade instructions to a future version release. I'll create a new issue for that.

**Review by cfabianski — APPROVED** [review]

**Pull request merged**
